# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    category_container:
        class: WebstoreBundle\Service\CategoryContainer
        arguments: [ '@doctrine.orm.entity_manager' ]
        calls:
          - method: getCategories
    picture_upload:
        class: WebstoreBundle\Service\UploadPicture
        arguments: ['@kernel']
    sort_products:
        class: WebstoreBundle\Service\SortProducts
        arguments: []
    validate:
        class: WebstoreBundle\Service\ValidationService
        autowire: true
    price_calculator:
        class: WebstoreBundle\Service\PriceCalculator
        arguments: ['@doctrine.orm.entity_manager']